[build]
  publish = "./"
  functions = "netlify/functions"

[[redirects]]
  from = "/thank-you.html"
  to = "/pages/thank-you.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  query = {path = ":path"}

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0" 