name: JOSS Paper Compilation

on:
  push:
    paths:
      - 'paper/**'
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile JOSS Paper
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf 